/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

const filePath = window.location.href + '/models/GroundPlane1.glb'

export default function GroundPlane1(props) {
  const texture = useTexture(window.location.href + '/images/flakes.png')

  const materialProps = {
    clearcoat: 1.0,
    clearcoatRoughness: 0,
    metalness: 0.65,
    roughness: 0.3,
    color: 'blue',

    transmission: 0.6,
    transparent: true
  }

  const material1 = new THREE.MeshPhysicalMaterial(materialProps)

  const group = useRef()
  const { nodes, materials } = useGLTF(filePath)

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0,.85, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.Mat1}
          scale={[10,10,10]}
        >

        </mesh>
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials.Mat2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_3.geometry}
          material={materials.Mat3}
        >
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_3.geometry}
          material={materials.Mat3}
        >
         <meshPhysicalMaterial {...materialProps} side={THREE.BackSide} /> 
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_4.geometry}
          material={materials.Mat4}
        >
          
        </mesh> */}
      </group>
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['Material.001']}
        position={[0, .85, 0.03]}
      >
        <meshPhysicalMaterial {...materialProps} side={THREE.BackSide} transmission={.9}/>

      </mesh> */}
    </group>
  )
}

useGLTF.preload(filePath)
